# -*- mode: ruby -*-
# vi: set ft=ruby :

### Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # All Vagrant configuration is done here. The most common configuration
    # For a complete reference, see the online documentation at vagrantup.com.

    ### Every Vagrant virtual environment requires a box to build off of.
    config.vm.box = "chef/debian-7.4"

    ### Port forwarding
    # mysql
    config.vm.network :forwarded_port, guest: 3306, host: 3306

    ### Run the bootstrap
    config.vm.provision :shell, :path => "bootstrap.sh"
end